name: Deploy to GitHub Pages

on:
  push:
    branches:
      - deploytest  # Cambia esto si deseas desplegar en una rama diferente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'  # Usa la versión de Node.js que prefieras

      - name: Install dependencies
        run: yarn install

      - name: Build and export Next.js app
        run: yarn build && yarn export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  
